# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devx < Formula
  desc "Supercharged local dev environment — Podman + Cloudflare Tunnels + Tailscale in one CLI"
  homepage "https://github.com/VitruvianSoftware/devx"
  version "0.37.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/VitruvianSoftware/devx/releases/download/v0.37.0/devx_darwin_amd64.tar.gz"
      sha256 "2af15e78238097addbde2b83b0c90229ba63a73000597f586ec4213094228f12"

      define_method(:install) do
        bin.install "devx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/VitruvianSoftware/devx/releases/download/v0.37.0/devx_darwin_arm64.tar.gz"
      sha256 "af420cde872f32d2250ab322089a1f4b5ad1fab332db439a710cb8759e3eb9e6"

      define_method(:install) do
        bin.install "devx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/VitruvianSoftware/devx/releases/download/v0.37.0/devx_linux_amd64.tar.gz"
      sha256 "8b49884896fb54471fb829ae2188ce86f4cdad87ee68544e28c07d0e5c9194ec"
      define_method(:install) do
        bin.install "devx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/VitruvianSoftware/devx/releases/download/v0.37.0/devx_linux_arm64.tar.gz"
      sha256 "42dad747b85c7515e03e2eaff33a5df12ad547b407d20ac2b431ab7018bd7bf8"
      define_method(:install) do
        bin.install "devx"
      end
    end
  end

  test do
    system "#{bin}/devx", "version"
  end
end
