# Generated by packages/peripherals/publish.sh in VitruvianSoftware/vitruvian-core; do not edit here.
class GravastarMouse < Formula
  desc "Status light and MCP server for the RGB LED of a GravaStar mouse"
  homepage "https://github.com/VitruvianSoftware/vitruvian-core/tree/main/packages/peripherals"
  url "https://github.com/VitruvianSoftware/vitruvian-core/releases/download/gravastar-mouse-v0.1.2/gravastar-mouse-0.1.2-macos.tar.gz"
  version "0.1.2"
  sha256 "51639c4191193bafadfbc0b84bb7d1072facda8bd69be2ca38850f66e2ee344e"
  license "MIT"

  depends_on macos: :sonoma

  def install
    bin.install "gravastar-mouse"
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/gravastar-mouse --version").strip
  end
end
