# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Homelab < Formula
  desc "Declaratively provision and manage multi-node K8s homelab clusters on macOS"
  homepage "https://github.com/VitruvianSoftware/homelab"
  version "1.6.0"
  license "Apache-2.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/VitruvianSoftware/homelab/releases/download/v1.6.0/homelab_1.6.0_darwin_amd64.tar.gz"
    sha256 "d23c50e03293969c08e7f041ef73c11474e32cbed702dc2ab49796e240ca4e6e"

    define_method(:install) do
      bin.install "homelab"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/VitruvianSoftware/homelab/releases/download/v1.6.0/homelab_1.6.0_darwin_arm64.tar.gz"
    sha256 "9eeb526b252a12725f74566e1ea973a685490108f444316628ab9cdc12e6d67a"

    define_method(:install) do
      bin.install "homelab"
    end
  end

  test do
    system "#{bin}/homelab", "version"
  end
end
