# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Homelab < Formula
  desc "Declaratively provision and manage multi-node K8s homelab clusters on macOS"
  homepage "https://github.com/VitruvianSoftware/homelab"
  version "1.0.2"
  license "Apache-2.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/VitruvianSoftware/homelab/releases/download/v1.0.2/homelab_1.0.2_darwin_amd64.tar.gz"
    sha256 "80b0e530467d3872028b70627172cb1781cb7ef4cf5a6757f90fffb49364b1dc"

    define_method(:install) do
      bin.install "homelab"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/VitruvianSoftware/homelab/releases/download/v1.0.2/homelab_1.0.2_darwin_arm64.tar.gz"
    sha256 "80f268c22b6c1bde3244038265ea0ce45f70d29a1818df3243d3f7c8c59e16f4"

    define_method(:install) do
      bin.install "homelab"
    end
  end

  test do
    system "#{bin}/homelab", "version"
  end
end
